databases:
  - name: utilities-db
    databaseName: utilities_db
    user: utilities_user
    plan: free

services:
  - type: web
    name: senpilot-utilities-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: utilities-db
          property: connectionString
